# 自己加上的
#=================================================================#
depth_supervision: True
bundle_loss: True
weak_depth: True
depth_patch: 5
viewer_show: False
debug: True
debug_tracker_sperpoint: True
track_every_frame: 5 #standard 1
#=================================================================#
# 下边是imap原生的
coarse: False #nice-slam: True
sync_method: loose #strict
scale: 0.1 #nice-slam: 1
verbose: True
occupancy: False #nice-slam: true
low_gpu_mem: True
grid_len: #what is grid_len
  coarse: 2 
  middle: 0.32 
  fine: 0.16
  color: 0.16
  bound_divisible: 0.32
pretrained_decoders: #load for what?
  coarse: pretrained/coarse.pt
  middle_fine: pretrained/middle_fine.pt # one ckpt contain both middle and fine
meshing:
  level_set: 10 #nice-slam: 0
  resolution: 256 # change to 512 for higher resolution geometry
  eval_rec: False
  clean_mesh: True
  depth_test: False
  mesh_coarse_level: False
  clean_mesh_bound_scale: 1.02
  get_largest_components: False
  color_mesh_extraction_method: render_ray_along_normal #nice-slam: direct_point_query
  remove_small_geometry_threshold: 0.2
tracking:
  #=================================================================#
  gt_camera: False
  #=================================================================#
  ignore_edge_W: 0 #20
  ignore_edge_H: 0 #20
  use_color_in_tracking: True
  device: "cuda:0"
  #=================================================================#
  handle_dynamic: False #nice-slam: True 
  #dynamic对在loss中对depth variance 大的进行了着重mask；我们也准备这么干
  #=================================================================#
  vis_freq: 50
  vis_inside_freq: 25
  w_color_loss: 0.5
  seperate_LR: False
  const_speed_assumption: True
  no_vis_on_first_frame: True
  lr: 0.001
  pixels: 5000 #nice-slam: 200
  iters: 50
mapping:
  device: "cuda:0"
  color_refine: True
  middle_iter_ratio: 0.4
  fine_iter_ratio: 0.6
  every_frame: 5
  #=================================================================#
  BA: False #nice-slam: true
  #=================================================================#
  BA_cam_lr: 0.0002 #nice-slam: 0.001
  fix_fine: True
  fix_color: False
  no_vis_on_first_frame: True
  #no_mesh_on_first_frame: True
  no_log_on_first_frame: True
  vis_freq: 50 # 传参失败，why？先直接写死在Mapper里了 5
  vis_inside_freq: 25 #each iteration 
  mesh_freq: 50 # 传参失败，why？先直接写死在Mapper里了 5
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  w_color_loss: 0.05 #nice-slam: 0.2
  frustum_feature_selection: False #nice-slam: True
  keyframe_selection_method: 'global' #nice-slam: 'overlap'
  save_selected_keyframes_info: True
  lr_first_factor: 5
  lr_factor: 1
  pixels: 5000 #nice-slam: 1000
  iters_first: 1500 # 传参失败，why？先直接写死在Mapper里了 1500
  iters: 300 #nice-slam: 60
  imap_decoders_lr: 0.0002 #nice-slam: not have this solution
  stage:
    coarse:
      decoders_lr: 0.0
      coarse_lr: 0.001
      middle_lr: 0.0
      fine_lr: 0.0
      color_lr: 0.0
    middle:
      decoders_lr: 0.0
      coarse_lr: 0.0
      middle_lr: 0.1
      fine_lr: 0.0
      color_lr: 0.0
    fine:
      decoders_lr: 0.0
      coarse_lr: 0.0
      middle_lr: 0.005
      fine_lr: 0.005
      color_lr: 0.0
    color:
      decoders_lr: 0.005
      coarse_lr: 0.0
      middle_lr: 0.005
      fine_lr: 0.005
      color_lr: 0.005
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  N_samples: 32
  N_surface: 0 #nice-slam: 16
  N_importance: 12 #nice-slam: 0
  lindisp: False
  perturb: 0.0
data:
  dim: 3
model:
  c_dim: 32
  coarse_bound_enlarge: 2
  pos_embedding_method: fourier



